name: dgtdriver
description: A DGT-Chessboard Driver written in pure Dart
version: 0.0.7
repository: https://github.com/mono424/dgtdriver
homepage: https://khad.im

environment:
  sdk: ">=2.7.0 <3.0.0"
