name: dgtdriver
description: A DGT-Chessboard Driver written in pure Dart
version: 0.2.4
repository: https://github.com/mono424/dgtdriver
homepage: https://khad.im

environment:
  sdk: ">=2.18.0 <3.0.0"
